name: Building APK

on:
  push:
    branches:
      - dev-dev

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build APK
        run: ./gradlew clean app:assembleNightly

      - name: Upload APK armeabi-v7a
        uses: actions/upload-artifact@v2
        with:
          name: armeabi-v7a
          path: ${{ github.workspace }}/app/build/outputs/apk/nightly/*-armeabi-v7a-*

      - name: Upload APK arm64-v8a
        uses: actions/upload-artifact@v2
        with:
          name: arm64-v8a
          path: ${{ github.workspace }}/app/build/outputs/apk/nightly/*-arm64-v8a-*

      - name: Upload APK x86
        uses: actions/upload-artifact@v2
        with:
          name: x86
          path: ${{ github.workspace }}/app/build/outputs/apk/nightly/*-x86-*

      - name: Upload APK x86_64
        uses: actions/upload-artifact@v2
        with:
          name: x86_64
          path: ${{ github.workspace }}/app/build/outputs/apk/nightly/*-x86_64-*
